
classdef JointCommand < ros.Message
    %JointCommand MATLAB implementation of intera_core_msgs/JointCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'intera_core_msgs/JointCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c8c85922d297da6209a089a906207e5d' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Mode' 'Names' 'Position' 'Velocity' 'Acceleration' 'Effort' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'mode' 'names' 'position' 'velocity' 'acceleration' 'effort' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        POSITIONMODE = int32(1)
        VELOCITYMODE = int32(2)
        TORQUEMODE = int32(3)
        TRAJECTORYMODE = int32(4)
    end
    properties
        Header
        Mode
        Names
        Position
        Velocity
        Acceleration
        Effort
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Header')
            obj.Header = val;
        end
        function set.Mode(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Mode');
            obj.Mode = int32(val);
        end
        function set.Names(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Names');
            obj.Names = cell(val);
        end
        function set.Position(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Position');
            obj.Position = double(val);
        end
        function set.Velocity(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Velocity');
            obj.Velocity = double(val);
        end
        function set.Acceleration(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Acceleration');
            obj.Acceleration = double(val);
        end
        function set.Effort(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Effort');
            obj.Effort = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.intera_core_msgs.JointCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.intera_core_msgs.JointCommand(strObj);
        end
    end
end
